[project]
name = "identity-service"
version = "0.1.0"
description = "Identity service"
readme = "README.md"
authors = [
    { name = "Cryder", email = "cronyx.developer@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
identity-service = "identity_service:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
