[project]
name = "identity-service"
version = "0.1.0"
description = "Identity service"
readme = "README.md"
authors = [
    { name = "Cryder", email = "cronyx.developer@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "grpcio>=1.84.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "uvloop>=0.22.1",
]

[project.scripts]
identity-service = "identity_service:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff]
line-length = 88
target-version = "py314"

select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
]

ignore = [
    "E501",
]

exclude = [
    ".git",
    ".venv",
    ".ruff_cache",
    ".idea",
    "venv",
    "build",
    "dist",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
